import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json([
    {
      id: '1',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    
    },

    {
      id: '2',
      name: 'Avocado - Premium',
      description: 'Creamy premium avocados, perfect for salads.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 2.49,
      stock: 40,
      category: { id: 'produce', name: 'Produce' },
      categoryId: 'produce',
      tags: [{ id: 'fresh', name: 'Fresh' }],
      brand: 'Fresh Valley',
      rating: 4.2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Artisan Sourdough Bread',
      description: 'Handmade sourdough bread with a crispy crust.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 6.99,
      stock: 15,
      category: { id: 'bakery', name: 'Bakery' },
      categoryId: 'bakery',
      tags: [{ id: 'artisan', name: 'Artisan' }],
      brand: 'Golden Crust',
      rating: 4.8,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      name: 'Wild Salmon Fillet',
      description: 'Wild-caught salmon fillet, rich in omega-3.',
      image: 'https://png.pngtree.com/png-clipart/20230403/original/pngtree-a-cup-of-mixed-fruit-salad-png-image_9023020.png',
      price: 18.99,
      stock: 8,
      category: { id: 'seafood', name: 'Seafood' },
      categoryId: 'seafood',
      tags: [{ id: 'wild', name: 'Wild' }],
      brand: 'Ocean Harvest',
      rating: 4.6,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '5',
      name: 'Organic Baby Spinach',
      description: 'Tender organic baby spinach leaves.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 3.49,
      stock: 30,
      category: { id: 'produce', name: 'Produce' },
      categoryId: 'produce',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Green Gardens',
      rating: 4.3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '6',
      name: 'Greek Yogurt - Vanilla',
      description: 'Creamy vanilla Greek yogurt.',
      image: 'https://png.pngtree.com/png-clipart/20230403/original/pngtree-a-cup-of-mixed-fruit-salad-png-image_9023020.png',
      price: 5.99,
      stock: 22,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'greek', name: 'Greek' }],
      brand: 'Mediterranean',
      rating: 4.4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '12',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    
    },
    {
      id: '7',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '8',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '9',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },  
    {
      id: '10',
      name: 'Organic Whole Milk',
      description: 'Fresh organic milk from grass-fed cows.',
      image: 'https://tse3.mm.bing.net/th/id/OIP.C2yRvmtMBxguk0l6W6bTTgHaGI?rs=1&pid=ImgDetMain&o=7&rm=3',
      price: 4.99,
      stock: 25,
      category: { id: 'dairy', name: 'Dairy' },
      categoryId: 'dairy',
      tags: [{ id: 'organic', name: 'Organic' }],
      brand: 'Farm Fresh',
      rating: 4.5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

  ]);
} 